# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 55e11ae2f4810e34e02e35e8fd258180681a51a7cd32e0e359b197984ac2c362fb1205deac57b0ecf87c764db8a9f29773ccc1e742de9826ece991dabf846a0c

test:
  secret_key_base: 695d096ad5920a1525056b3a5f46148e8ca8bd9999e58eec58cd400d88de4579e4dd6ae795274ebb473bbb990bf87b72f68289488a9060687145c61e3587187a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
